import "~/styles/globals.css";
import Navbar from "./_components/navbar";

import { Inter } from "next/font/google";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en">

      <body className=" min-h-screen bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
      <Navbar />
     {children}
      </body>
    </html>
  );
}
